# Generated by Django 2.1.5 on 2019-02-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0004_auto_20190212_1009'),
        ('clustermaster', '0011_auto_20190215_0500'),
        ('elections', '0004_auto_20190211_0910'),
        ('voters', '0007_auto_20190214_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_vote', models.DateTimeField(auto_now=True)),
                ('vote_is_good', models.BooleanField(default=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clustermaster.Booth')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidates.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Posts')),
                ('vote_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.VoterTypes')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voters.Voters')),
            ],
        ),
    ]
