# Generated by Django 2.1.5 on 2019-02-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_value',
            new_name='votertype',
        ),
    ]
