# Generated by Django 2.1.5 on 2019-02-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('voter_class', models.CharField(blank=True, max_length=9, null=True)),
                ('has_voted', models.CharField(max_length=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.VoterTypes')),
            ],
            options={
                'verbose_name_plural': 'voters',
                'managed': True,
            },
        ),
    ]
