# Generated by Django 2.1.5 on 2019-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='has_voted',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='voters',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
