# Generated by Django 2.1.5 on 2019-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_auto_20190207_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voters',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
