# Generated by Django 2.1.5 on 2019-02-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_auto_20190212_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.VoterTypes'),
        ),
    ]
