# Generated by Django 2.1.5 on 2019-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('election_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(default='General Election', max_length=50)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='VoterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Voter Types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('year', 'election_number')},
        ),
    ]
