# Generated by Django 2.1.5 on 2019-02-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0003_auto_20190205_2055'),
        ('voters', '0002_auto_20190205_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('candidate_class', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='media/candidates/images')),
                ('logo', models.ImageField(upload_to='media/candidates/logos')),
                ('slogan', models.CharField(max_length=30)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Posts')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voters.Voters')),
            ],
        ),
    ]
