# Generated by Django 2.1.5 on 2019-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_class',
            field=models.CharField(max_length=20),
        ),
    ]
