# Generated by Django 2.1.5 on 2019-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20190207_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='active',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
