# Generated by Django 2.1.5 on 2019-02-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=30)),
                ('status', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clustermaster.Cluster'),
        ),
    ]
