# Generated by Django 2.1.5 on 2019-02-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_auto_20190212_1009'),
        ('clustermaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='status',
            new_name='booth_status',
        ),
        migrations.AddField(
            model_name='booth',
            name='assigned_voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='voters.Voters'),
        ),
    ]
