# Generated by Django 2.1.5 on 2019-02-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20190211_0910'),
        ('clustermaster', '0002_auto_20190212_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election'),
        ),
    ]
