# Generated by Django 2.1.5 on 2019-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustermaster', '0003_cluster_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
