# Generated by Django 2.1.5 on 2019-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustermaster', '0004_auto_20190214_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
