# Generated by Django 2.1.5 on 2019-02-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20190211_0910'),
        ('clustermaster', '0005_auto_20190214_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('username', 'password'), ('election', 'location')},
        ),
    ]
