# Generated by Django 2.1.5 on 2019-02-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clustermaster', '0008_auto_20190214_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clustermaster.Cluster'),
        ),
    ]
