# Generated by Django 2.1.5 on 2019-02-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clustermaster', '0009_auto_20190214_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='election',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election'),
        ),
    ]
