# Generated by Django 2.1.5 on 2019-02-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clustermaster', '0010_auto_20190215_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elections.Election'),
        ),
    ]
